[general]
live_config_reload = true
import = ["/Users/stuermer/.config/alacritty/colors.toml"]

[env]
TERM = "alacritty"

[window]
decorations = "full"
opacity = 0.8
startup_mode = "Maximized"
title = "Terminal"

[window.padding]
x = 5
y = 5

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[colors]
draw_bold_text_with_bright_colors = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 300

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[cursor.style]
blinking = "Off"
shape = "Beam"

[terminal.shell]
program = "/bin/zsh"

