[general]
import = ["/Users/stuermer/.config/alacritty/colors.toml"]
live_config_reload = true

[env]
TERM = "alacritty"

[window]
padding = { x = 5, y = 5 }
decorations = "Full"
opacity = 0.7
startup_mode = "Windowed"
title = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 11
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[colors]
# see colors.toml
draw_bold_text_with_bright_colors = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 300

[selection]
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''
save_to_clipboard = true

[cursor.style]
blinking = "Off"
shape = "Beam"

[terminal.shell]
program = "/bin/zsh"

