export ZSH="$HOME/.oh-my-zsh"

# https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="awesomepanda"

# oh-my-posh
eval "$(/opt/homebrew/bin/oh-my-posh init zsh --config /opt/homebrew/opt/oh-my-posh/themes/kushal.omp.json)"

# https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#plugins
plugins=(
  brew
  colorize
  docker
  docker-compose
  encode64
  extract
  gh
  git
  gpg-agent
  gradle
  history-substring-search
  jira
  rsync
  rust
)

# Init script
source $ZSH/oh-my-zsh.sh

# custom scripts
source $HOME/.zsh/alias.zsh
source $HOME/.zsh/android.zsh
source $HOME/.zsh/colors.zsh
source $HOME/.zsh/credentials.zsh
source $HOME/.zsh/env.zsh
source $HOME/.zsh/history.zsh
source $HOME/.zsh/java.zsh
source $HOME/.zsh/locale.zsh
source $HOME/.zsh/options.zsh
source $HOME/.zsh/ssh.zsh

# zoxide
eval "$(zoxide init zsh)"

